/********************************************************************
Copyright 2012,TD-Tech. Co., Ltd.
Filename:      dao_common.hpp
Author:        XiaoLongguang
Created:       2012/11/24 09:01
Description:
*********************************************************************/

#ifndef UBP_PLATFORM_MODULES_DAO_DAO_COMMON_HPP_
#define UBP_PLATFORM_MODULES_DAO_DAO_COMMON_HPP_

#include "platform/modules/trace/ubp_trace.hpp"
/* 定义此宏是为了解决WINDOWS平台单实例类对象在dll和exe中并非同一实例的bug */
/* dll中需要export，使用时需要import */
#ifdef WIN32
#ifdef DAO_EXPORT
#define DAO_IMPORT_EXPORT __declspec(dllexport)
#else//NOT DAO_EXPORT
#define DAO_IMPORT_EXPORT __declspec(dllimport)
#endif//DAO_EXPORT
#else//NOT WIN32
#define DAO_IMPORT_EXPORT
#endif//WIN32

#define DAO_FUN_TRACE(FUNC) UBP_FUNC_TRACE("PLATFORM.DAO",FUNC)
#define DAO_FUN_INFO(FUNC) UBP_FUNC_INFO("PLATFORM.DAO",FUNC)
#define UBP_DAO_DEBUG(LOG) UBP_LOGGER_DEBUG("PLATFORM.DAO", LOG)
#define UBP_DAO_INFO(LOG) UBP_LOGGER_INFO("PLATFORM.DAO", LOG)
#define UBP_DAO_WARN(LOG) UBP_LOGGER_WARN("PLATFORM.DAO", LOG)
#define UBP_DAO_ERROR(LOG) UBP_LOGGER_ERROR("PLATFORM.DAO", LOG)
#define UBP_DAO_FATAL(LOG) UBP_LOGGER_FATAL("PLATFORM.DAO", LOG)

#define DAO_CHECK_CONDITION_RETURN(CONDITION,ERRMSG) \
  CHECK_CONDITION_RETURN(UBP_DAO_ERROR,CONDITION,ERRMSG)

#define DAO_CHECK_CONDITION_RETURN_FAIL(CONDITION,ERRMSG) \
  CHECK_CONDITION_RETURN_FAIL(UBP_DAO_ERROR,CONDITION,ERRMSG)

#define DAO_CHECK_CONDITION_RETURN_ERRCODE(CONDITION,ERROR_CODE) \
  CHECK_CONDITION_RETURN_ERRCODE(UBP_DAO_ERROR,CONDITION,ERROR_CODE)

#define DAO_CHECK_CONDITION_RETURN_NULL(CONDITION,ERRMSG) \
  CHECK_CONDITION_RETURN_NULL(UBP_DAO_ERROR,CONDITION,ERRMSG)

#define DAO_CHECK_VAL_RETURN(CHECK_VAL,ERRMSG) \
  CHECK_VAL_RETURN(UBP_DAO_ERROR,CHECK_VAL,ERRMSG)

#define DAO_CHECK_VAL_RETURN_FAIL(CHECK_VAL,ERRMSG)\
  CHECK_VAL_RETURN_FAIL(UBP_DAO_ERROR,CHECK_VAL,ERRMSG)

#define DAO_CHECK_VAL_RETURN_NULL(CHECK_VAL,ERRMSG) \
  CHECK_VAL_RETURN_NULL(UBP_DAO_ERROR,CHECK_VAL,ERRMSG)

#define DAO_CHECK_VAL_RETURN_ERRCODE(CHECK_VAL,ERRMSG) \
  CHECK_VAL_RETURN_ERRCODE(UBP_DAO_ERROR,CHECK_VAL,ERRMSG)

#define DAO_CHECK_NULL_RETURN(PTR,ERRMSG) \
  CHECK_NULL_RETURN(UBP_DAO_ERROR,PTR,ERRMSG)

#define DAO_CHECK_NULL_RETURN_FAIL(PTR,ERRMSG) \
  CHECK_NULL_RETURN_FAIL(UBP_DAO_ERROR,PTR,ERRMSG)

#define DAO_CHECK_NULL_RETURN_NULL(PTR,ERRMSG) \
  CHECK_NULL_RETURN_NULL(UBP_DAO_ERROR,PTR,ERRMSG)

#define DAO_CHECK_NULL_RETURN_ERRCODE(PTR,ERROR_CODE) \
  CHECK_NULL_RETURN_ERRCODE(UBP_DAO_ERROR,PTR,ERROR_CODE)

//todo:接口返回具体的错误码
#define UBP_DAO_SUCCESS 0
#define UBP_DAO_FAIL -1
#define UBP_DAO_NO_RES 1

#define UBP_DAO_NULL_PTR -2

#define UBP_DAO_IN_TRANS -3
#define UBP_DAO_NOTIN_TRANS -4
#define UBP_DAO_TRANS_FIN -5

#define UBP_DAO_IN_SESS -6
#define UBP_DAO_NOTIN_SESS -7
#define UBP_DAO_SESS_REQ -8

#define UBP_DAO_RECOVERABLE -9
#define UBP_DAO_DEADLOCK -10
#define UBP_DAO_CON_LOST -11
#define UBP_DAO_TIMEOUT -12
#define UBP_DAO_OBJ_NOTEXIST -13
#define UBP_DAO_OBJ_EXIST -14
#define UBP_DAO_OBJ_CHANGED -15
#define UBP_DAO_RES_NOTCACH -16
#define UBP_DAO_DATA_EXC -17

#define UBP_DAO_ABS_CLASS -18
#define UBP_DAO_NOTYPE_INFO -19

#define UBP_DAO_UNKNOWN_SCHEMA -20

#define UBP_DAO_ENC_MAX_STR_LEN 512



#endif  //UBP_PLATFORM_MODULES_DAO_DAO_COMMON_HPP_
