// The computer generated IDispatch wrapper class created by Visual C++ Microsoft

// Note: do not modify the contents of this file. 
// If this class is re generated by the Visual C++ Microsoft, your changes will be covered.


#include "stdafx.h"
#include "elte_playerctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CElte_playerctrl1

IMPLEMENT_DYNCREATE(CElte_playerctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CElte_playerctrl1 attribute

/////////////////////////////////////////////////////////////////////////////
// CElte_playerctrl1 operate
